# Generated by Django 5.2 on 2025-04-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.PositiveIntegerField(choices=[('активен', 'активен'), ('завершен', 'завершен'), ('отменен', 'отменен')], max_length=32),
        ),
    ]
