# Generated by Django 5.2 on 2025-04-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0002_alter_auction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.PositiveIntegerField(choices=[('активен', 'активен'), ('завершен', 'завершен'), ('отменен', 'отменен')]),
        ),
    ]
