# Generated by Django 5.2 on 2025-04-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0005_alter_auction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('активен', 'активен'), ('завершен', 'завершен'), ('отменен', 'отменен')], max_length=32),
        ),
    ]
