# Generated by Django 5.2 on 2025-04-23 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0006_alter_auction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='auction_app.car'),
        ),
    ]
